### ISSUE TITLE
Transpose cluster overview table

### ISSUE THREAD

**Issue by tsprlng** [lmenezes/elasticsearch-kopf#253]
Thanks a lot for this project, it's been incredibly helpful as an elasticsearch beginner dealing with unpredictable behaviour!

This is just a suggestion I thought I'd make to see what the prevailing opinion is...

For some use cases of elasticsearch (in my case, logstash) it's quite likely there will be many more indices than nodes – therefore, on the cluster overview, it would be helpful to have the columns headed by nodes and the indices shown in rows.

i.e.: The cluster table should have its rows and columns flipped / transposed.

This would mean that easy vertical scrolling would be possible over all the many indices, and if they have long names (again… logstash) they would also fit better on the page.

Questions:
- Does anyone else agree?
- Are there in fact many cases where the current layout would in fact be preferred over this transposed one?; i.e. do people often run many more nodes than they have indices?.
- Should the cluster overview template support rendering both ways?

I'd be really happy to try and contribute code to achieve this, but thought it best to ask for an opinion first.

**Comment by lmenezes** [comment]
hey @tsprlng 
glad you like kopf :)

About transposing the cluster overview table... There was someone else who once suggested the same thing. 

I'd say flipping rows x tables could work better for some people. In my particular case it wouldn't(I do have almost twice as many indices as I do nodes... but I still have +- 20 nodes in my clusters).

As kopf is also what I use for managing my cluster, I do not want to change that. But, if you are interested in working out an alternate view(and if this actually turns out to be interesting to other people), we could find a way of making this "switchable". But probably will be easier to create a completely separate alternate view.

One interesting thing to know is, rendering 100+ indices + shards at once can be very CPU intensive and would probably make everything else really slow(I have tried things like this before, and things such as filtering out indices and so on work like crap). And having 100+ indices, you will need filtering :)

Anyway, if you are really interested we can talk about it :)

**Comment by lmenezes** [comment]
@tsprlng will close this for now, but let me know if you are interested in making it transposable.
