### ISSUE TITLE
Animate shard copy progress

### ISSUE THREAD

**Issue by jannemann** [lmenezes/elasticsearch-kopf#297]
It would be nice to see the progress of a shard that is been transfered to another server.
Maybe by filling the rectangle by percentage of  "index.size.percent".

**Comment by a-lustin-parc** [comment]
+1

**Comment by darkoc** [comment]
+1
Also holds for recovery on cluster restart.

**Comment by lmenezes** [comment]
hey all,
kopf is going into maintenance mode only, and will only be getting updates in order to keep functioning with newer ES versions.

I'm developing a replacement for kopf, even though it's still not yet feature compatible. This is something I might finally get working there.

Thanks for the suggestion nevertheless :)
