### ISSUE TITLE
Can't connect to elastic as standalone.

### ISSUE THREAD

**Issue by dosmanak** [lmenezes/elasticsearch-kopf#303]
Hello, redacted site's elastic search is available in browser on port 9200.
{
  "status" : 200,
  "name" : "redacted",
  "cluster_name" : "redactedes",
  "version" : {
    "number" : "1.6.0",
    "build_hash" : "cdd3ac4dde4f69524ec0a14de3828cb95bbb86d0",
    "build_timestamp" : "2015-06-09T13:36:34Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
The tool claims following:

 [2015-09-21 14:02:16] Error executing request:
[2015-09-21 14:02:16] {"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://redacted:9200/","data":{},"params":{},"headers":{"Accept":"application/json, text/plain, */*"}}
[2015-09-21 14:02:16] REST API output:

**Comment by lmenezes** [comment]
could you describe your setup please?
- is kopf installed on elasticsearch, or are you running that directly from somewhere else?
- which version of kopf?

in the meanwhile, could you check the Network tab on your browser and see if this request might be failing because CORS is not enabled on elasticsearch?

**Comment by dosmanak** [comment]
Yes. I am sorry. I had setup CORS on other node. So I am not sure this was the issue since I was trying several nodes.
I am using it standalone version from my Linux Mint desktop.
After I run npm install, it works just fine.

Thanks for the response.
