### ISSUE TITLE
None data node does not appear in Cluster menu

### ISSUE THREAD

**Issue by jeesim2** [lmenezes/elasticsearch-kopf#309]
It seems none data node does not appear in client section.
but appears in node section.

![cluster](https://cloud.githubusercontent.com/assets/1100831/10235484/d98cfe46-68d7-11e5-90db-fadbea70f83d.png)

here is nodes settings
501-data false, master true <--- not appear in cluster menu
502-data false, master true <--- not appear in cluster menu
503-data true, master true
60X data true, master false

please check it out!
thanks!.

**Comment by lmenezes** [comment]
@jeesim2 this is the expected behaviour. Even though this tab says cluster, what it really means(and probably I should change this in the feature) is shard allocation. As non data nodes cannot host shards, it's pointless and cluttering to show them there.

**Comment by jeesim2** [comment]
@lmenezes  thanks for the explanation.
btw, I think if cluster section is the default view, we want to see which one is master or which node is over loading at that place.
And I'd prefer to use cluster section than node section for monitoring the basic load.
because cluster section's indicators are more stands out and more recognizable than node sections' values.
it will be more convenient if non data node displayed at the cluster section too.

**Comment by lmenezes** [comment]
@jeesim2 it would be really unlikely that a master node only would be overloaded. normally you would only see this on a data node(which is visible there).

Also, that might work for smaller clusters, but for large cluster, you cannot see all nodes in that screen anyway(for me, I can see all data nodes, but if I include client/master nodes, I can't).

kopf is at the moment a administration tool, not so much a monitoring tool, and I think overloading it with so much monitoring(which is again not good, since it only gives you the current state of the cluster) is not the right way.

sorry for that :)

**Comment by jeesim2** [comment]
OK! got it! Agree with you :)

btw, do you have or are there feature request about query notebook?
some feature like save favorite query, bookmark, the upgraded version of rest section.
it will be greate!

**Comment by lmenezes** [comment]
I don't think so. The issue with this is that this information would need to either be kept on the browser or on the cluster. 

I'm currently considering extending the functionality of kopf to offer proper monitoring(and this implies storing data on the cluster). I guess this could happen there as well.

Haven't had a lot of time lately, but hopefully will have more time in the near future.
