### ISSUE TITLE
Show integrated index name

### ISSUE THREAD

**Issue by garyelephant** [lmenezes/elasticsearch-kopf#315]
Kopf hides the trailing of index name when index name is long enough.This makes it hard to distinguish  among different indices, such as `0a0968231e9a422781499c9016c1f7a7-2015.09.21`, `0a0968231e9a422781499c9016c1f7a7-2015.09.21`.

![image](https://cloud.githubusercontent.com/assets/2291859/10684009/cf552a26-797a-11e5-94d8-640ef7803a2b.png)

**Comment by lmenezes** [comment]
hiding the trailing of the index name is intended, otherwise the table would look all messed up.

for auto generated names like this(I'm not sure if its meaningful somehow), the indices are sorted alphabetically(so there is some logic behind it that allows you to navigate) and can also be filtered by name(if you are looking for one specifically).

other than that, I guess the best I could offer is a tooltip. changing the width of the column or breaking lines are not really a good option.

**Comment by garyelephant** [comment]
I think offer a tooltip to show integrated index name when the mouse is hovering over the index name is a good idea.
