### ISSUE TITLE
Cat thread_pool API

### ISSUE THREAD

**Issue by nbuso** [lmenezes/elasticsearch-kopf#326]
I was wondering why the thread_pool cat call is commented out. As a monitoring interface, these calls could help understanding the status of the cluster.

**Comment by lmenezes** [comment]
@nbuso mostly because of time constraints :)
When I started development for the cat apis section, I expected that parsing of the output would be pretty straight forward, almost like split on whitespace, and everything will work out. It isn't as easy as that :)

Some of the values *might* contain a space(node name), some of the values are right aligned, some left aligned and so on. 

I still hope to get back at this and have it generic for all cat apis, but haven't really found the time.

**Comment by kevinliteon** [comment]
@lmenezes 
>  I expected that parsing of the output would be pretty straight forward, almost like split on whitespace, and everything will work out. It isn't as easy as that :)

Hmm,
and with `/_cat/thread_pool?format=json` ?

**Comment by lmenezes** [comment]
@kevinliteon honestly I didn't know I could request format=json. that makes things much easier yes :)

On the other hand, I have somehow abandoned development for kopf. Since ES 5 won't allow site plugins anymore, and I don't wan't to transform kopf into a kibana plugin, I have started developing a kopf replacement, as a standalone app. It's far from being feature equivalent with kopf, but I hope to have a public first release soon -> https://github.com/lmenezes/cerebro

I will integrate the cat api in there as well, it's actually one of the easy ones. thanks for the heads up :)
