### ISSUE TITLE
Not able to do anything in Kopf

### ISSUE THREAD

**Issue by StanleyEbenezer123** [lmenezes/elasticsearch-kopf#358]
I am new to ELK and Kopf. I installed ES and Kopf in my system (localhost). Kopf does not allow me to create or delete indices and REST API's also don't work. The common error i get while i perform any of this is 'request was not successful "" '. I don't get any error messages too.
I started facing this issue after a .Kibana file was created automatically after i installed Kibana.
Pls help.

**Comment by hackel** [comment]
I just started getting this issue after using Kopf without incident for the last year.  Not sure what is going on.  Running Kopf 2.1.1 on ES 2.3.2.  I'm getting 403 Forbidden responses from ES for some reason, but only when I query from Kopf.  Querying from my angular app still works fine.

I also noticed that I get a 403 trying to retrieve font-awesome, so the UI looks a bit messed-up.  Not sure if these are related.

**Comment by hackel** [comment]
Figured out that this was caused by the ES CORS settings.  In my elasticsearch.yml, my `http.cors.allow-origin` didn't include the port.  Once I added :9200 to the end, Kopf started working fine again.  I know ES 2.3 had some CORS changes, so I guess it is being more strict about what it will serve to plugins.  For a local/dev instance, you can just set `http.cors.allow-origin: "*"`.

**Comment by lmenezes** [comment]
@hackel thanks for commenting on this :)
