### ISSUE TITLE
Many text inputs so tiny they are annoying to work with.

### ISSUE THREAD

**Issue by FrankyBoy** [lmenezes/elasticsearch-kopf#362]
For instance that one:
![image](https://cloud.githubusercontent.com/assets/265792/16147528/df20a95c-3483-11e6-953e-5bd21d49cd9f.png)

Please either make them bigger by default or add some way to resize them.

**Comment by lmenezes** [comment]
hey @FrankyBoy 
I'm no longer actively developing kopf(since it won't be supported by ES 5.0), but focusing my efforts in creating a replacement for it(https://github.com/lmenezes/cerebro). 
at the moment, it does not have all of kopf features, but it should soon have it. I will take your comments into account for this new app, but I won't be investing anytime in kopf.
thanks for the feedback :)
