### ISSUE TITLE
Any Plan to monitoring search and indexing rate.

### ISSUE THREAD

**Issue by ishara** [lmenezes/elasticsearch-kopf#366]
Any plan to monitoring search rate / latency and index rate/latency  ?

**Comment by lmenezes** [comment]
@ishara hey there. I'm currently not actively developing kopf anymore, since amongst other things, elasticsearch 5.0 won't support site plugins(like kopf). 
I'm currently developing another application to replace kopf(https://github.com/lmenezes/cerebro), but at this moment it does not have all of kopf features. hopefully it will have, and more.
